Parameters:
  UITag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number
    Default: 0

  UITargetGroup:
    Type: String

  Cluster:
    Type: String

  UIRepository:
    Type: String

Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: aldis-ui
          ContainerPort: 3000
          TargetGroupArn: !Ref UITargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-aldis
      ContainerDefinitions:
        - Name: aldis-ui
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${UIRepository}:${UITag}
          EntryPoint:
            - hs
            - build
            - -p
            - 3000
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: 3000
              HostPort: 80
          Environment:
            - Name: UITag
              Value: !Ref UITag
